name: libais CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PIP_WHEEL_DIR: /home/runner/.cache/pip/wheels
  PIP_FIND_LINKS: file:///home/runner/.cache/pip/wheels

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [
          '3.13',
          '3.14',
        ]
    steps:
      - name: Add required sources and pkgs
        run: |
          sudo apt-get update
          sudo apt-get install --yes gcc g++ cmake ninja-build

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Before install
        run: |
          mkdir --parents --verbose ${{ env.PIP_WHEEL_DIR }}
          pip install setuptools --upgrade
          pip install pytest --upgrade

      - name: Install
        run: CC=g++ pip install .\[tests\] --upgrade
        
      - name: Script
        run: |
          cmake -G Ninja -B build -S . -DENABLE_ASAN=ON && ninja -C build && ctest --test-dir build --output-on-failure
          py.test ais test --cov=ais --cov-report term-missing
